services:

  spring:
    container_name: backend-2-spring
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    networks:
      - backend-2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:backend_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - PF_HOSTNAME=pf
      - PF_PORT=8080

  pf:
    container_name: product-fetcher
    build:
      context: .
      dockerfile: Dockerfile.pf
    ports:
      - "9999:8080"
    networks:
      - backend-2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:product_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s


networks:
  backend-2: